line-length = 100
fix = false
output-format = "grouped"

extend-exclude = [
    "__pycache__",
    ".cache",
]

[lint]
select = [
    "B",    # flake8-bugbear
    "C4",   # flake8-comprehensions
    "FIX",  # flake8-fixme
    "D",    # pydocstyle/flake8-docstrings
    "N",    # pep8-naming
]

ignore = [
    # pydocstyle
    "D100",
    "D104",
    "D105",
    "D107",
    "D203",
    "D212",
    "D214",
    "D215",
    "D301",
    "D400",
    "D401",
    "D402",
    "D404",
    "D405",
    "D406",
    "D407",
    "D408",
    "D409",
    "D410",
    "D411",
    "D412",
    "D413",
    "D414",
    "D416",
    "D417",
    # pep8-naming
    "N802",
    "N806",
    "N815",
    # ruff
    "N999",
]

[lint.per-file-ignores]
"test_*.py" = [
    "D101",
    "D103",
]
